### ISSUE TITLE
[Suggestion] Support "uppperTersity"

### ISSUE THREAD

**Issue by nwparker** [desktop-dart/duration#29]
Support "uppperTersity"

Example:
If you have `Duration(hours: 25)`, you may want it to print `hours 25` instead of `days 1 hours 24`

Adding an "upperTersity" option would enable such behavior

**Comment by tejainece** [comment]
Thanks for the suggestion. This is fixed by the commit https://github.com/desktop-dart/duration/commit/f6040f3b5b5d587d62ebde37e93f6139b9b57c0e.

Published as 3.0.10.
