### ISSUE TITLE
Remove debug logging from printDuration

### ISSUE THREAD

**Issue by jeffjose** [desktop-dart/duration#31]
Looks like `printDuration` has a debug logging in. See [here](https://github.com/desktop-dart/duration/blob/bace00a96308453b175069bae75ca09f04f486dd/lib/src/duration.dart#L137)

Reproduced below
```dart
String printDuration(Duration duration,
    {DurationTersity tersity = DurationTersity.second,
    DurationLocale locale = const EnglishDurationLocale(),
    String spacer,
    String delimiter,
    String conjugation,
    bool abbreviated = false}) {
  final String fmt = prettyDuration(duration,
      tersity: tersity,
      locale: locale,
      spacer: spacer,
      delimiter: delimiter,
      conjunction: conjugation,
      abbreviated: abbreviated);
  print(fmt);
  return fmt;
}
```

**Comment by jeffjose** [comment]
Opened https://github.com/desktop-dart/duration/pull/33 and https://github.com/desktop-dart/duration/pull/32

**Comment by tejainece** [comment]
Guys what part of **print**Duration dont you understand. It is meant to print. If you just want to convet use `prettyDuration`. Also read the docs.
