### ISSUE TITLE
Remove unnecessary print

### ISSUE THREAD

**Issue by iakrevetkho** [desktop-dart/duration#45]
https://github.com/desktop-dart/duration/blob/93d10155ad9bb7bd313cdf1ddd42b492d8782a60/lib/src/duration.dart#L137

**Comment by shilangyu** [comment]
From README:

> **NOTE**: Use `prettyDuration`, `prettySeconds`, `prettyMilliseconds` instead of `printDuration`, `printSeconds`, `printMilliseconds` if you only want to format/convert and don't want to print to console!

Still, if I wanted to print it I would print it myself, weird design decision
