### ISSUE TITLE
Can not parse duration from a string with weeks

### ISSUE THREAD

**Issue by GrupoDO** [desktop-dart/duration#47]
If I try to parse the duration '19w, 3d, 5m'  I got an exception "Invalid duration format". But if I try to parse the duration '138d, 5m' I got the correct result.

The error is because the regex does not expect the 'w' format: final match = RegExp(r'^(\d+)(d|h|m|s|ms|us)$').matchAsPrefix(part);

So I can go from a duration to a text but I can't go from a text to a duration.

Can you fix this please?

Thank you!

**Comment by tejainece** [comment]
Sorry for the delay. This is now fixed and published as 3.0.8.
