### ISSUE TITLE
upperTersity param not working in printDuration

### ISSUE THREAD

**Issue by tusharlock10** [desktop-dart/duration#53]
I am trying to limit the upperTersity to days, but its taking the default value of weeks. The code is -

```
final playTime = Duration(minutes: value); // value = 14966
final humanizedTime = printDuration(
    playTime,
    abbreviated: true,
    tersity: DurationTersity.hour,
    upperTersity: DurationTersity.day,
); // output = 1w, 3d, 9h
```

I have tested the tersity param and its working. upperTersity is not working with any value of DurationTersity, it is always giving weeks

**Comment by tejainece** [comment]
Thanks for the bug report. I have fixed it and pushed it to pub.dev as 3.0.11.
