### ISSUE TITLE
PrettyDuration with abbreviated : true has incorrect identifier for minutes.

### ISSUE THREAD

**Issue by bruntzcreative** [desktop-dart/duration#55]
This code snippet produces `5h, 33min, 20s`.
I expected `min` to be abbreviated to `m`.
```dart
  prettyDuration(
    Duration(milliseconds: 20000000),
    abbreviated: true,
  );
```

**Comment by bdlukaa** [comment]
`m` is the abbreviation for meters. `min` is the abbreviation for minutes

**Comment by bruntzcreative** [comment]
`m` Is ok if there is no possibility of confusion with meters IMO. I think having an option to use it would be helpful for smaller displays.
