### ISSUE TITLE
Handle negative durations properly

### ISSUE THREAD

**Issue by Keithcat1** [desktop-dart/duration#62]
Dart 2.18, Windows 10 64-bit
This code:
```dart
import "package:duration/duration.dart";
void main() {
	print(prettyDuration(Duration(seconds: -1), abbreviated: false));
}
```
prints:
59 seconds                                                                                                                                                              
when I run it, instead of something like 1 second ago.

**Comment by tejainece** [comment]
Fixed in 4.0.0
